# Generated by Django 3.2.7 on 2021-09-13 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100, unique=True, verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'db_table': 'UnitMeasurement',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=80, unique=True, verbose_name='Producto')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Descuento')),
                ('categoty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.category')),
                ('unit_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.unitmeasurement')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Product',
                'ordering': ['id'],
            },
        ),
    ]
