# Generated by Django 3.2.7 on 2021-09-13 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Tipo de entrega')),
            ],
            options={
                'verbose_name': 'Tipo de entrega',
                'verbose_name_plural': 'Tipos de entrega',
                'db_table': 'DeliveryType',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('product', models.ManyToManyField(to='Product.Products')),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedido',
                'db_table': 'OrderDetail',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=80, unique=True, verbose_name='Tipo de pago')),
                ('description', models.CharField(max_length=80, unique=True, verbose_name='Numero de cuenta')),
            ],
            options={
                'verbose_name': 'Tipo de pago ',
                'verbose_name_plural': 'Tipos de pago',
                'db_table': 'PaymentType',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeAccountingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80, unique=True, verbose_name='Tipo documento contable')),
            ],
            options={
                'verbose_name': 'Tipo de documento contable ',
                'verbose_name_plural': 'Tipos de documentos contables',
                'db_table': 'TypeAccountingDocument',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='Fecha de pedido')),
                ('status', models.BooleanField(default=True, verbose_name='Confirmado')),
                ('payment_reference', models.CharField(max_length=80, verbose_name='Referencía de pago')),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.deliverytype')),
                ('order_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Order.orderdetail')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.paymenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'verbose_name': 'Cabecera de pedido',
                'verbose_name_plural': 'Cabeceras de pedido',
                'db_table': 'HeaderOrder',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='Fecha')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Referencia')),
                ('order_header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Order.orderheader')),
                ('type_accounting_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.typeaccountingdocument')),
            ],
            options={
                'verbose_name': 'Documento contable',
                'verbose_name_plural': 'Documentos contables',
                'db_table': 'AccountingDocument',
                'ordering': ['id'],
            },
        ),
    ]
