# Generated by Django 3.2.7 on 2021-09-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80, unique=True, verbose_name='Ciudad')),
                ('postal_code', models.PositiveSmallIntegerField(unique=True, verbose_name='Código postal')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'Town',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, unique=True, verbose_name='Identificación')),
            ],
            options={
                'verbose_name': 'Identificación',
                'verbose_name_plural': 'Identificaciones',
                'db_table': 'TypeId',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80, unique=True, verbose_name='Tipo de usuario')),
            ],
            options={
                'verbose_name': 'Tipo de usuario',
                'verbose_name_plural': 'Tipos de usuario',
                'db_table': 'TypeUser',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombres')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='Identificación')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.town')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.typeid')),
                ('type_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.typeuser')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'User',
                'ordering': ['id'],
            },
        ),
    ]
